---
# tasks file for wazuh-agent

- name: Include OS-specific vars.
  include_vars: "{{ item }}.yml"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version}}"
    - "vars/{{ ansible_distribution }}"
    - "vars/{{ ansible_os_family }}"
  tags: vars

- name: Download Wazuh Agent installer.
  ansible.builtin.get_url:
    url: "{{ wazuh_agent_package_url }}"
    dest: /tmp/{{ wazuh_agent_package_name }}
    checksum: "{{ wazuh_agent_package_checksum }}"

- include_tasks: setup-{{ ansible_os_family }}.yml
