---

- name: Install Wazuh Agent.
  ansible.builtin.yum:
    name: /tmp/{{ wazuh_agent_package_name }}
    state: present
  environment:
    WAZUH_MANAGER: "{{ wazuh_agent_manager_url }}"
    WAZUH_AGENT_GROUP: "{{ wazuh_agent_groups }}" 
    WAZUH_AGENT_NAME: "{{ inventory_hostname }}"
  notify: Enable and start Wazuh Agent
