---
# handlers file for wazuh-agent

- name: Set Wazuh Agent service state
  ansible.builtin.service:
    name: "{{ wazuh_agent_service_name }}"
    state: "{{ wazuh_agent_service_state }}"
    enabled: "{{ wazuh_agent_service_enabled }}"
